name: Release Crate

on:
  push:
    tags:
      - 'v*.*.*'  # Adjust the pattern as needed.

jobs:
  release:
    uses: ./.github/workflows/rust-ci.yaml
    with:
      run-publish: true
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
